Fix/validation
Wealize/validator pull request #4
Opened 2023-02-01 16:54 UTC by arnauZap

# Don't forget to add Jira issue related code to the title 😇

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix

## Description
Create QrValidation screen and vinculación to backend.
## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
![Captura de pantalla 2023-02-01 a las 17 52 59](https://user-images.githubusercontent.com/114933020/216109173-ab4f39ef-f4f7-4ac4-a62c-73e8e38ce012.png)
![Captura de pantalla 2023-02-01 a las 17 53 22](https://user-images.githubusercontent.com/114933020/216109179-e67feaa3-af4c-47db-9dc3-7c902ea7ec32.png)

## [optional] What gif best describes this PR or how it makes you feel?

2023-02-02 07:58 UTC, victoriatnp requested changes
Revisa los errores en los test

2023-02-02 08:03 UTC, victoriatnp requested changes

2023-02-02 10:41 UTC, emenocal07 commented on src/pages/validateQR.tsx
> +const IndexContainer = styled(Layout)`
Solo esto que sacaría los estilos a otro archivo

2023-02-06 09:03 UTC, victoriatnp approved these changes

2023-02-06 09:03 UTC, merged