Features/verify v2
Wealize/validator pull request #9
Opened 2023-07-13 07:40 UTC by arnauZap

# Don't forget to add Jira issue related code to the title 😇

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix

## Description
Added a new certification verification path called VERIFY_V2.
Changed the method of sending requests from fetch to axios.
Added error handling to send the request to the new verification route in case the original route fails.
## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

## [optional] What gif best describes this PR or how it makes you feel?

2023-07-14 09:39 UTC, Iraia26 approved these changes

2023-07-17 07:12 UTC, emenocal07 requested changes

2023-07-17 07:12 UTC, emenocal07 commented on src/pages/validateQR/index.tsx
>        // console.log('error', error)
Tratar el error acá?

2023-07-17 07:25 UTC, emenocal07 reviewed
Por fa agrega tomas de pantalla del resultado de la tarea @arnauZap

2023-07-17 10:10 UTC, emenocal07 approved these changes

2023-07-17 11:38 UTC, merged